name: CI/CD_Pipeline_AWS
env:
  EB_PACKEGE_S3_BUCKET_NAME : "cicd.pipeline"
  EB_APLICATION_NAME        : "ci.cd_beanstalk"
  EB_ENVIROMENT_NAME        : "Cicdbeanstalk-env-1"
  EB_DEPLOY_PACKAGE_NAME    : "deploy.zip"
  AWS_REGION_NAME           : "eu-central-1"

on:
  push:
    branches: 
      - master 
 
jobs:
  ci_part:
    runs-on: ubuntu-latest
    
    steps:
      - name: GIT clone repo
        uses: actions/checkout@v3
        with:
          submodules: true
        
      - name: Generate deployment package
        run: zip -r ${{ env.EB_DEPLOY_PACKAGE_NAME }} ./ -x *.git*
        
      - name: Config AWS credentials 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id      : ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key  : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region             : ${{ env.AWS_REGION_NAME }}
          
      - name: Copy to S3
        run: aws s3 cp ${{ env.EB_DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKEGE_S3_BUCKET_NAME }}/
        
  cd_part:
    runs-on: ubuntu-latest
    needs: [ci_part]
    
    steps:
      - name: Config AWS credentials 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id      : ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key  : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region             : ${{ env.AWS_REGION_NAME }}
          
      - name: Create Beanstalk  App
        run: |
           aws elasticbeanstalk create-application-version \
           --application-name ${{ env.EB_APLICATION_NAME }} \
           --source-bundle S3Bucket="${{ env.EB_PACKEGE_S3_BUCKET_NAME }}",S3Key="${{ env.EB_DEPLOY_PACKAGE_NAME }}" \
           --version-label "Ver-${{ github.sha }}" \
           --description "CommitSHA-${{ github.sha }}"
           
      - name: Deploy Beanstalk App
        run: aws elasticbeanstalk update-environment --environment-name ${{ env.EB_ENVIROMENT_NAME }} --version-label "Ver-${{ github.sha }}"
          
     
