name: CI/CD_Pipeline_AWS
env:
  EB_PACKEGE_S3_BUCKET_NAME : "cicd.pipeline"
  EB_APLICATION_NAME        : "ci.cd_beanstalk"
  EB_ENVIROMENT_NAME        : "ci.cd_beanstalk-env"
  DEPLOY_PACKAGE_NAME       : "ci/cd_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "eu-central-1"

on:
  push:
    branches: 
      - master 
 

jobs:
  ci_part:
    runs-on: ubuntu-latest
    
    steps:
      - name: GIT clone repo
        uses: actions/checkout@v3
        with:
          submodules: true
        
      - name: Generate deployment package
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x '*.git*'
        
      - name: Config AWS credentials 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id      : ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key  : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region             : ${{ env.AWS_REGION_NAME }}
          
      - name: Copy to S3
        run: aws s3 cp ./ s3://${{ env.EB_PACKEGE_S3_BUCKET_NAME }}/
   
     
